name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libxdo-dev
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Check formatting
      run: cargo fmt --check
      continue-on-error: true
    - name: Check
      run: cargo clippy --verbose --locked --all-features
    - name: Run tests
      run: cargo test --verbose --locked --all-features
